David
codewear-study/react-calculator pull request #1
Opened 2019-12-23 07:28 UTC by SangYeoop

계산기 일단 만들긴했는데 ㅠㅠㅠㅠ React의 방식은 조금아닌거같아요.. 
그래도 되도록 ReactComponent랑 props써볼려고 노력은했습니다....

2019-12-25 12:14 UTC, Parkhyunseo commented
https://www.notion.so/native/PR-0a45d9ffdddb4f49821a2164c8221e25#1fd147f6fd774374a0443ba0dfaea7e8
위 링크로 들어가 PR 명명 규칙을 확인하고 수정해주세요.

2019-12-25 12:16 UTC, Parkhyunseo commented
우측에 있는 Reviews를 모두 체크해주세요.
Assignees를 본인으로 체크해주세요.
Label을 enhancements로 체크해주세요.

2019-12-25 12:33 UTC, Parkhyunseo requested changes
고생하셨습니다! 아주 빠른 시간내에 정말 잘 구현 하셨네요.
Javascript에 익숙하지 않은 상태로 이정도로 개발하기 힘들었을 텐데 정말 대단합니다!

다만 조금 아쉬운 점을 몇 개 이야기 드리겠습니다.
1. 요구사항을 잘 지키지 못했다.
~~요구사항에 있는 실수 연산, Clear Button, Back Button등이 구현되지 못했습니다.
조금 더 노력하셔서 남은 기능 까지 모두 구현해주시길 바랍니다.~~
구현이 되어있었는데, 확인을 못했었네요! BackButton은 구현 해주시고 나머지 기능들은 컴포넌트로 분리 해야합니다!

2. React를 제대로 사용하지 못했습니다.
지금은 React를 사용한 것도 안한 것도 아니라고 생각이 됩니다. 차라리 먼저 React를 사용하지 않은 채로 완성을 시킨 그 다음에 React와 연결 해보는 걸 추천합니다.

고생하셨습니다!
코드 리뷰 받은 내용 잘 숙지하시고! 정리하시면 더 좋고! 금주 스터디에서 이야기 해주셔도 좋습니다.
리뷰 반영 부탁드릴게요~

2019-12-25 12:33 UTC, Parkhyunseo commented on src/App.js
> +    <div>
최상위에 div를 넣으신 이유가 있을까요?

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorController.js
> +    static value = "0";
static에 남용이 심한 것 같습니다.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorController.js
> +import CalculatorModel from './CalculatorModel';
이름에 View, Controller, Model이 들어가는건 좋은 명명법이 아닙니다.
CalculatorPanel, Calculator등의 이름으로 바꿔주세요

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorController.js
> +    static inputNumberFromButton(number) {
CalculatorController라는 클래스가 너무 많은 기능(함수)를 가지고 있기 때문에 함수명이 장황해지는 것 같습니다. 
예를들어 React Component로 만들어서 Button 클래스나 함수를 따로 만든다면 onClick 이라는 이벤트에 inputNumber라는 함수를 연결 시키고 keyDown 이벤트에 inputNumber를 연결 시켜 단순한 명명법으로 바뀌고, CalculatorController에서 책임을 분리 시킬 수 있습니다.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorController.js
> +        document.getElementById('result').value = CalculatorController.value;
React를 사용한다면 document.getElementById와 같은 방식으로 DOM에 접근하는건 좋은 방식이 아닙니다.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorController.js
> +    static inputOpeartorFromButton(oper) {
oper라는 파라미터 명은 깔끔하지 못한 이름인 것 같습니다.
`operator` 또는 `op`정도를 추천합니다.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorController.js
> +        if(oper === '='){
이런 상황에서는 switch문이 더 보기 좋을 것 같습니다.
또는 javascript 객체를 이용해서 함수를 반환 받는게 코드가 더 깔끔합니다.
javascript의 객체는 [링크](https://developer.mozilla.org/ko/docs/Learn/JavaScript/Objects/Basics)에서 확인하세요.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorModel.js
> +let Calculator = {
let을 쓴 이유가 있을까요? 
let과 const, var에 대한 이해가 아직 부족한 것 같습니다.
[링크](https://hianna.tistory.com/314)에서 간단히 확인해보세요.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorModel.js
> +      if(number === "0")
Error가 발생했을 때 throw를 해보는 것도 좋은 방법입니다.

2019-12-25 12:33 UTC, Parkhyunseo commented on src/CalculatorTemplate.js
> +                <button onClick={CalculatorController.inputClearButton.bind(this)}>clear</button>
기회가 되신다면 이번 스터디에서 bind함수에 대해 한 번 설명해주시면 좋을 것 같아요 :)

2019-12-25 12:51 UTC, Parkhyunseo commented on src/CalculatorController.js
> +    static inputNumberFromButton(number) {
decimalpoint (.) 의 중복 박지 코드가 빠져있습니다.

2019-12-25 13:07 UTC, SangYeoop commented on src/CalculatorController.js
> +import CalculatorModel from './CalculatorModel';
아 넵 알겠습니다!

2019-12-25 13:08 UTC, SangYeoop commented on src/CalculatorController.js
> +    static inputOpeartorFromButton(oper) {
넵 이것도 수정해보겠습니다

2019-12-25 13:32 UTC, SangYeoop commented on src/CalculatorController.js
> +    static value = "0";
static을 사용한 이유가 저는 처음에 원래 controller에 input함수를 짜고 숫자버튼을 클릭했을때 이 함수들을 연결해주고 싶었는데 연결해서 보니까 숫자 1,2,3,4,5,6,7,8,9마다 서로 다른 controller의 객체를 참조하고 있었습니다 . 그래서 controller를 단 한개만 존재하게하고 싶었는데 그것에 대한 구현방법을 제대로 정하지못해서 함수들과 변수들에 전부 static을 부여하고 사용했습니다.

2019-12-25 13:34 UTC, SangYeoop commented on src/CalculatorModel.js
> +let Calculator = {
const는 내부 변수의 값이 바뀌지 않을때 사용하는것이라고 생각하고 있었습니다. Calculator클래스는 내부 최종결과에 대한 변수 값이 계속 바뀌므로 const가 아닌 let을 사용해주는게 맞다고 생각했습니다.

2019-12-25 13:35 UTC, SangYeoop commented on src/CalculatorModel.js
> +      if(number === "0")
넵 다음에 코딩을할때  에러에 대해서 throw하는것도 생각해서 코딩해보도록 하겠습니다.

2019-12-25 13:35 UTC, SangYeoop commented on src/CalculatorController.js
> +    static inputNumberFromButton(number) {
헐...대박

2019-12-25 13:35 UTC, SangYeoop commented on src/CalculatorTemplate.js
> +                <button onClick={CalculatorController.inputClearButton.bind(this)}>clear</button>
bind가 되게 헷갈렸는데 notion에 한번 정리해보도록 하겠습니다!

2019-12-25 13:36 UTC, SangYeoop commented on src/CalculatorController.js
> +        if(oper === '='){
else문을 사용하지 않기로했었는데 switch문을 사용하면 안될거 같았습니다.

2019-12-25 23:33 UTC, HodaeSsi commented
고생 많으셨습니다!

2019-12-27 01:36 UTC, Parkhyunseo commented on src/CalculatorModel.js
> +let Calculator = {
const는 내부 변수의 값이 바뀌지 않을 때 사용하는게 아니라 const를 사용하는 객체, 함수, 변수의 값이 변경되지 않는겁니다. 정확히 다시 한 번 정리하는게 좋겠어요.

2019-12-27 01:38 UTC, Parkhyunseo commented on src/CalculatorController.js
> +        if(oper === '='){
오... switch문을 if else라고 생각은 안해봤는데, 듣고보니 그렇네요.
그렇다면 객체를 사용해서 해결하는 걸 추천합니다.

2019-12-27 01:40 UTC, Parkhyunseo commented on src/CalculatorController.js
> +    static value = "0";
약간 시작이 잘못되어서 문제가 되는 부분을 하나 하나 막아가는 방식으로 개발 되는 것 같습니다.
이럴 때, static을 사용하려할 때 이게 맞는 방식인가. 꼭 static을 써야하나? 처음 개발 방식이 잘못 된게 아닐까? 라는 의심을 해보길 바랍니다.

2019-12-27 04:51 UTC, PParkJy reviewed
submit을 눌러야 제출이 되는 거였군요.....

2019-12-27 04:51 UTC, PParkJy commented on src/CalculatorController.js
> +                return;
지금 case가 나눠져있고, 그에 따른 코드가 Calculator.~~ 빼고 그 밑부분은 동일하잖아요.
저도 이렇게 코드를 중복되게 짜는 편이라 이거를 좀 더 깔끔하게 짜는 방법이 있을까요??

2019-12-27 04:55 UTC, Parkhyunseo commented on src/CalculatorController.js
> +                return;
중복 되는 부분은 함수로 빼는게 가장 깔끔합니다! 
중복되는 부분만 함수로 빼고 값이 다른 부분은 인자값으로 받아서 인자에 따라 다르게 실행되게 하면 위 코드도 많이 줄일 수 있을 것 같아요

2019-12-27 15:00 UTC, Tetramad reviewed
수고하셨습니다. 👐

2019-12-27 15:00 UTC, Tetramad commented on src/App.js
> +  );
```js
return (
    <CalculatorPanel></CalculatorPanel>
);
```
```js
return <CalculatorPanel />;
```
저는 위 보다는 아래가 더 좋습니다. 괄호와 태그 짝을 맟추는 것의 의미가 있는가 싶습니다.

2019-12-27 15:00 UTC, Tetramad commented on src/CalculatorPanel.js
> +                <NumberButton value= "9"></NumberButton>
반복문을 안 쓰시다니👍

2019-12-27 15:00 UTC, Tetramad commented on src/ClearButton.js
> +            </button>
```js
<button onClick={CalculatorController.inputClearButton.bind(this)}>
    clear
</button>
```
이렇게 쓰는 게 "clear"라는 문자가 눈에 더 잘 들어올 것 같습니다.

2019-12-27 15:00 UTC, Tetramad commented on src/NumberButton.js
> +            </button>
`src/ClearButton.js`와 동일합니다.
```js
<button onClick={CalculatorController.inputNumberFromButton.bind(this, this.props.value)}>
  {this.props.value}
</button>
```

2019-12-27 15:00 UTC, Tetramad commented on src/OperatorButton.js
> +            <button onClick={CalculatorController.inputOpeartorFromButton.bind(this, this.props.operator)}>{this.props.operator}</button>
엄... 일관성이 없으시네요.

2019-12-27 15:00 UTC, Tetramad commented on src/ResultField.js
> +           <input id="result" ref={ref =>{this.input = ref;}}></input>
`ref`변수가 자칫 헷갈리게 할 수 도 있는 것 같습니다.

2019-12-27 15:55 UTC, SangYeoop commented on src/NumberButton.js
> +            </button>
clearbutton은 inputclearbutton이구 위에건 inputnumberbutton입니당

2019-12-27 15:57 UTC, SangYeoop commented on src/ResultField.js
> +           <input id="result" ref={ref =>{this.input = ref;}}></input>
ref변수는 코드를 수정하려다가 잠시 멈췄었는데 깜빡했네요

2019-12-27 15:58 UTC, SangYeoop commented on src/OperatorButton.js
> +            <button onClick={CalculatorController.inputOpeartorFromButton.bind(this, this.props.operator)}>{this.props.operator}</button>
ㅠㅠ 어느면에서 일관성이 없는지 알려주시면 리뷰해주시면 고쳐볼게요!

2019-12-27 16:02 UTC, SangYeoop commented on src/App.js
> +    <div>
음 처음에 return을 할때 기존의 형태가아니라 button일일이 App에 넣어줄려고했었는데 다시 생각해보니까 좀 아닌거같아서 따로 Panel형태로 만드는과정에서 코드 빼는걸 깜빡한것같습니다 ㅠ 수정했습니당.

2019-12-27 16:34 UTC, SangYeoop commented on src/CalculatorPanel.js
> +                <NumberButton value= "9"></NumberButton>
제생각인데 간단한 프로그램에서는 이렇게 쓰는게 더 가독성측면에서 괜찮다고 생각합니다. ㅎㅎ

2019-12-27 17:52 UTC, SangYeoop commented on src/CalculatorController.js
> +                return;
넵 저도 동의합니다 ㅠㅠ

2019-12-28 10:19 UTC, Tetramad commented on src/NumberButton.js
> +            </button>
`src/ClearButton.js`랑 동일한 이유로 줄바꿈하는 것이 좋다고 생각한다는 뜻입니다.

2019-12-28 10:20 UTC, Tetramad commented on src/OperatorButton.js
> +            <button onClick={CalculatorController.inputOpeartorFromButton.bind(this, this.props.operator)}>{this.props.operator}</button>
줄바꿈부분을 말하는 거였습니다.

2019-12-28 14:14 UTC, SangYeoop commented on src/OperatorButton.js
> +            <button onClick={CalculatorController.inputOpeartorFromButton.bind(this, this.props.operator)}>{this.props.operator}</button>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-06-25 04:06 UTC, closed without merging